#!/bin/bash
# This is the setup script for the workstation container. Use it to set the stage for your terraform training, demo, or lab.
set -e

# Allow instruqt time to do its thing
sleep 10

# Source important environment variables
mkdir -p /root/.local/share/code-server/User

# Set the user's working directory with the set-workdir script, then in subsequent challenges the user will always start in that directory.
mkdir /root/workspace
/bin/set-workdir /root/workspace

# Ensure we load /etc/profile.d/instruqt-env.sh
echo "source /etc/profile.d/instruqt-env.sh" >> /root/.bashrc
