#!/bin/bash
set -x

# Allow instruqt time to inject variables and settings
sleep 30

until [ -e /var/lib/cloud/instance/boot-finished ]; do
  echo "Waiting for cloud init to do its thing."
  sleep 5
done

# Make sure we have all our environment variables
echo "source /etc/profile.d/instruqt-env.sh" >> /root/.bashrc
source /root/.bashrc

# Set up the web server for instructions
apt-get update --fix-missing
apt-get -y install nginx
cd /tmp
wget --quiet https://storage.googleapis.com/instruqt-hashicorp-tracks/terraform-shared/mdwiki-0.6.2.zip
unzip mdwiki-0.6.2.zip
cp mdwiki-0.6.2/mdwiki.html /var/www/html/index.html
git clone https://github.com/scarolan/terraform-foundations-azure tfa
cp -r tfa/images /var/www/html
cp tfa/AZURE.md /var/www/html/index.md

# Upgrade terraform to 1.0.5
# This should be removed once the workstation is updated.
wget https://releases.hashicorp.com/terraform/1.0.5/terraform_1.0.5_linux_amd64.zip -O /tmp/terraform.zip
unzip -o /tmp/terraform.zip -d /usr/local/bin
chmod +x /usr/local/bin/terraform

# Set up git-aware prompt via .bash_profile
# TODO: Move git prompt repo to internal
echo "source /root/.bash_profile" >> /root/.bashrc
git clone https://github.com/scarolan/bash-git-prompt.git ~/.bash-git-prompt --depth=1
cat <<-EOM > ~/.bash_profile 
if [ -f "$HOME/.bash-git-prompt/gitprompt.sh" ]; then
    GIT_PROMPT_ONLY_IN_REPO=1
    source $HOME/.bash-git-prompt/gitprompt.sh
fi
EOM

# Go home
cd /root

# Setup script finished
echo "Setup script finished."
