#!/bin/bash
set -x

# Allow instruqt time to inject variables and settings
sleep 30

until [ -e /var/lib/cloud/instance/boot-finished ]; do
  echo "Waiting for cloud init to do its thing."
  sleep 5
done

# Make sure we have all our environment variables
echo "source /etc/profile.d/instruqt-env.sh" >> /root/.bashrc
source /root/.bashrc

# Set up the web server for instructions
apt-get update --fix-missing
apt-get -y install nginx

cd /tmp
wget --quiet https://storage.googleapis.com/instruqt-hashicorp-tracks/terraform-shared/mdwiki-0.6.2.zip
unzip mdwiki-0.6.2.zip
cp mdwiki-0.6.2/mdwiki.html /var/www/html/index.html
curl https://raw.githubusercontent.com/scarolan/terraform-foundations-azure/main/AZURE.md -o /var/www/html/index.md

# Go home
cd /root

# Setup script finished
echo "Setup script finished."
