version: "2"
containers:
- name: cloud-client
  image: gcr.io/instruqt/cloud-client
  shell: /bin/bash
  ports:
  - 80
virtualmachines:
- name: workstation
  image: instruqt-hashicorp/terraform-workstation-prod
  shell: /bin/bash
  environment:
    FOO: bar
  machine_type: n1-standard-1
azure_subscriptions:
- name: azuresubscription
  roles:
  - Contributor
